### ISSUE TITLE
One extra field in Boiler:HotWater

### ISSUE THREAD

**Issue by Ski90Moo** [NREL/OpenStudio#5112]
Issue overview
--------------

The following error appears when simulating Boiler:HotWater:
   ** Severe  ** Output:PreprocessorMessage="ExpandObjects" has the following Fatal conditions:
   **   ~~~   ** SEVERE: Too many fields were found for the object: Boiler:HotWater
   **   ~~~   ** Number
   **   ~~~   ** expected=[17]
   **   ~~~   ** Number found=[18]
   **  Fatal  ** Preprocessor condition(s) cause termination.

## Current Behavior

EnergyPlus input file shows 18 fields:

Boiler:HotWater,
  Boiler Hot Water 1,                     !- Name
  NaturalGas,                             !- Fuel Type
  Autosize,                               !- Nominal Capacity {W}
  0.8,                                    !- Nominal Thermal Efficiency
  LeavingBoiler,                          !- Efficiency Curve Temperature Evaluation Variable
  Boiler Efficiency,                      !- Normalized Boiler Efficiency Curve Name
  Autosize,                               !- Design Water Flow Rate {m3/s}
  0,                                      !- Minimum Part Load Ratio
  1,                                      !- Maximum Part Load Ratio
  1,                                      !- Optimum Part Load Ratio
  Node 19,                                !- Boiler Water Inlet Node Name
  Node 24,                                !- Boiler Water Outlet Node Name
  99,                                     !- Water Outlet Upper Temperature Limit {C}
  ConstantFlow,                           !- Boiler Flow Mode
  0,                                      !- On Cycle Parasitic Electric Load {W}
  1,                                      !- Sizing Factor
  General,                                !- End-Use Subcategory
  0;                                      !- Off Cycle Parasitic Fuel Load {W}

Latest EnegyPlus InputOutput reference 23.2.0 indicates that there should be up to 19 fields.  Number expected should be 19, not 17.
## Steps to Reproduce

1.
2.
3.
4.

### Environment

Some additional details about your environment for this issue (if relevant):
 - Platform (Operating system, version):
![Screenshot 2024-03-14 081615](https://github.com/NREL/OpenStudio/assets/69771412/0247d370-6bfa-4893-a2b5-dfc8168fdff5)

 - Version of OpenStudio (if using an intermediate build, include SHA):
![image](https://github.com/NREL/OpenStudio/assets/69771412/a9c46949-282d-4bf3-af0c-73c38bd019cf)

**Comment by buildingman07** [comment]
I am having the same issue in OpenStudio when trying to add a boiler to a hot water loop.

**Comment by eringold** [comment]
This is an issue that EnergyPlus had running ExpandObjects, which @jmarrec fixed here: https://github.com/NREL/EnergyPlus/pull/10288
EnergyPlus will attempt to run ExpandObjects when an HVACTemplate is detected in the idf. OpenStudio creates HVACTemplate objects when 'Use Ideal Air Loads' for an OS:ThermalZone is 'Yes', i.e. when the 'Turn On Ideal Air Loads' box is checked in for a Thermal Zone tab in the OpenStudioApplication. One way to work around this failure is to not have that box selected for any zones. An alternative way to use Ideal Air Loads that does not use HVACTemplates is to specify a ZoneHVACIdealLoadsAirSystem object, as in [this](https://github.com/BuildingPerformanceSimulation/openstudio-measures/tree/38da5fd9ab285fa1d0af0a5141875a16a27eb17d/lib/measures/ideal_air_loads_zone_hvac) measure (which replaces HVAC in all zones, so might not be directly applicable to your use case without modification).

**Comment by laiamusach** [comment]
I have the same problem but I don't have ideal loads on and I don't understand how you solved it.

**Comment by eringold** [comment]
@laiamusach can you share the model, or a way to reproduce the error?

**Comment by laiamusach** [comment]
[design.zip](https://github.com/user-attachments/files/16102233/design.zip)
I hope you can downloade it. Now I solve it but I still get some warnings that kind of mess with accurate results. This is an analysis of a small house that only uses heating with a diesel boiler. However, it says I don't have cooling loads and I quite don't understand what that means. I would be so glad if you could go a bit through the warnings cause I am a bit lost.

**Comment by Ski90Moo** [comment]
@laiamusach It appears your thermal zones do not have a cooling thermostat assigned.  This is not the forum for troubleshooting your model.  Please see unmethours.com.

**Comment by laiamusach** [comment]
Sorry for the inconveniences, I posted it in unmethours.com a few days ago as well.
